### PR TITLE
feature(Img): add reverse prop for right-alignment

### LINKED ISSUE #9: Option to right align image

### PR DESCRIPTION
**Pull request by chantastic**
Issue:

Now simple way to right-align Img.

Job Story:

When I'm showing a chat conversation, I want to right-align the Img, So
that I can demonstrate sides of a conversation.

Solution:

Add `reverse` prop to Img that flips float styles.

Outcome/side effects:

The way I'm spreading `props` every nested component gets the `reverse` prop.

References, ticket, issues:

Resolves #9

### CODE REVIEW

**Comment by chantastic** [comment]
@KyleAMathews, this should fix #9. Let me know if it works for your needs.

**Comment by KyleAMathews** [comment]
Code-wise it looks great (Check it out at https://relaterocket.co/about/) but api-wise, I expected I'd put the reverse on the Media component not the Img component. It took me several minutes to figure out otherwise. Putting `reverse` on the Media component makes sense to me as you're reversing the entire component tree not just the image.

**Comment by chantastic** [comment]
Agreed. After playing with it, I was feeling the same way. I'll fix it up.

**Comment by chantastic** [comment]
So cool to see this in an App I didn't make. Thanks for sharing :)

**Comment by KyleAMathews** [comment]
:) agreed, it is fun.

**Comment by chantastic** [comment]
I haven't found a good method for using parent-based context in 13.x. Are you familiar with one? I'm wondering if I should just punt on this until the official transition in 14.x. Thoughts?

The net result is still easily achieved by passing a style-object to `Img` with `{ float: 'right', marginLeft: 10 }`

**Comment by KyleAMathews** [comment]
Punting until 0.14 sounds fine as that's pretty close.

**Comment by chantastic** [comment]
feature added in [v0.1.0](https://github.com/chantastic/react-media-object/tree/v0.1.0), just merged into master.

**Pull request closed without merging**
