### PR TITLE
"main" field should point to compiled version

### PR DESCRIPTION
**Pull request by KyleAMathews**

### CODE REVIEW

**Comment by KyleAMathews** [comment]
Hmmm... which also means the compiled version needs to be distributed.

**Comment by chantastic** [comment]
@KyleAMathews so sorry about the delay on these. apparently i didn't get auto-subscribed to my own repos. who knew!

I'm gonna dive into these tonight. I used Jed Watson's component generator. I'd like to figure out what his thinking was in this.

**Comment by KyleAMathews** [comment]
:+1: thanks!

**Comment by chantastic** [comment]
Ok. I think this one is now resolved. I copied this commit from the an generator-react-component: https://github.com/JedWatson/generator-react-component/commit/ad5196583f9060c751a3e915b12f706a74cca226

Also ran the built in `npm run build`, which looks like it wired everything up correctly. I'm going to try it out in an app before I close this.

**Comment by chantastic** [comment]
tag `0.0.3` (on master) looks good to me. let me know if you continue to have any trouble. thanks for the PR :)

**Pull request closed without merging**
