### PR TITLE
React shouldn't be a dependency

### PR DESCRIPTION
**Pull request by KyleAMathews**

### CODE REVIEW

**Comment by chantastic** [comment]
@JedWatson thoughts on this?

**Comment by JedWatson** [comment]
These days I generally don't include react as a dependency, because it can cause all sorts of issues if you end up with duplicate `react` instances and npm doesn't give you control over that.

In my packages the simplest way I've found of enforcing the React dependency is to set it as a `devDependency` _and_ `peerDependency`. Still not perfect, you have to be liberal with the versions (so `>=0.13.`) which doesn't protect from untested API changes in new versions, but imo safer than not declaring it at all. (maybe?)

**Comment by JedWatson** [comment]
Just realised this is still the way I've got it set up in my component generator, so that's been updated now.

**Comment by chantastic** [comment]
Thanks @JedWatson I'll check that update out and pull in any additional changes.

Thanks for all your help @KyleAMathews!!!

**Pull request merged**
